# Generated by Django 4.2.16 on 2025-11-21 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this notification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_triggered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
