# Generated by Django 4.2.16 on 2025-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0011_delete_mutedconversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchat",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="groupchat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="group_picture",
            field=models.ImageField(
                blank=True,
                help_text="Group profile picture",
                null=True,
                upload_to="group_pictures/",
            ),
        ),
    ]
