# Generated by Django 4.2.16 on 2025-07-08 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
