# Generated by Django 4.2.23 on 2025-09-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
    ]
