# Generated by Django 4.2.16 on 2025-08-25 10:58

from django.db import migrations


def update_to_linkedin_reactions(apps, schema_editor):
    """Update all existing reactions to LinkedIn style"""
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Mapping from Facebook to LinkedIn reactions
    mapping = {
        'love': 'heart',      # love -> heart
        'laugh': 'laugh',     # laugh -> laugh (same)
        'wow': 'applaud',     # wow -> applaud
        'angry': 'sad',       # angry -> sad
        'like': 'like',       # like -> like (same)
        'sad': 'sad',         # sad -> sad (same)
    }
    
    for old_type, new_type in mapping.items():
        count = Reaction.objects.filter(reaction_type=old_type).update(reaction_type=new_type)
        if count > 0:
            print(f"Updated {count} '{old_type}' reactions to '{new_type}'")


def reverse_to_facebook_reactions(apps, schema_editor):
    """Reverse back to Facebook style"""
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Reverse mapping
    reverse_mapping = {
        'heart': 'love',
        'laugh': 'laugh',
        'applaud': 'wow',
        'like': 'like',
        'sad': 'sad',
    }
    
    for new_type, old_type in reverse_mapping.items():
        Reaction.objects.filter(reaction_type=new_type).update(reaction_type=old_type)


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0005_convert_facebook_to_linkedin_reactions"),
    ]

    operations = [
        migrations.RunPython(update_to_linkedin_reactions, reverse_to_facebook_reactions),
    ]
