# Generated by Django 4.2.16 on 2025-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0006_final_linkedin_reactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("applaud", "👏"),
                    ("heart", "❤️"),
                    ("support", "🤝"),
                    ("laugh", "😂"),
                    ("sad", "😢"),
                ],
                max_length=20,
            ),
        ),
    ]
