# Generated by Django 4.2.16 on 2025-09-07 13:15

from django.db import migrations


def approve_all_existing_posts(apps, schema_editor):
    """Update all existing posts to be approved"""
    Post = apps.get_model('posts_app', 'Post')
    Post.objects.filter(is_approved=False).update(is_approved=True)
    print(f"Updated {Post.objects.count()} posts to be auto-approved")


def reverse_approve_all_posts(apps, schema_editor):
    """Reverse migration - set posts back to unapproved (optional)"""
    # We won't actually reverse this as it would break the functionality
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0008_auto_approve_posts"),
    ]

    operations = [
        migrations.RunPython(approve_all_existing_posts, reverse_approve_all_posts),
    ]
