# Generated by Django 4.2.16 on 2025-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment and Bullying'), ('inappropriate', 'Inappropriate Content'), ('false_information', 'False Information'), ('violence', 'Violence or Threats'), ('copyright', 'Copyright Infringement'), ('other', 'Other')], max_length=50),
        ),
    ]
