# Generated by Django 4.2.16 on 2025-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0012_merge_20251022_0853"),
    ]

    operations = [
        # Remove columns only if they exist and update status field
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Remove approved_at column if it exists
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts_app_post' AND column_name='approved_at') THEN
                    ALTER TABLE posts_app_post DROP COLUMN approved_at;
                END IF;
                
                -- Remove approved_by_id column if it exists
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts_app_post' AND column_name='approved_by_id') THEN
                    ALTER TABLE posts_app_post DROP COLUMN approved_by_id;
                END IF;
                
                -- Remove decline_reason column if it exists
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts_app_post' AND column_name='decline_reason') THEN
                    ALTER TABLE posts_app_post DROP COLUMN decline_reason;
                END IF;
                
                -- Update status field choices - change 'pending' to 'published' if exists
                UPDATE posts_app_post SET status = 'published' WHERE status = 'pending';
                UPDATE posts_app_post SET status = 'published' WHERE status = 'approved';
                
                -- Ensure status field has correct default
                ALTER TABLE posts_app_post ALTER COLUMN status SET DEFAULT 'published';
            END $$;
            """,
            reverse_sql="""
            -- Reverse operations (add columns back if needed)
            ALTER TABLE posts_app_post ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE NULL;
            ALTER TABLE posts_app_post ADD COLUMN IF NOT EXISTS approved_by_id INTEGER NULL;
            ALTER TABLE posts_app_post ADD COLUMN IF NOT EXISTS decline_reason TEXT NULL;
            ALTER TABLE posts_app_post ALTER COLUMN status SET DEFAULT 'pending';
            """
        ),
    ]
