# Generated by Django 4.2.16 on 2025-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "messaging_app",
            "0002_remove_attachment_file_type_remove_message_reply_to_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
