# Generated by Django 4.2.16 on 2025-08-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0007_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
