# Generated by Django 4.2.16 on 2025-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0008_message_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
