# Generated by Django 4.2.16 on 2025-08-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0013_groupmemberrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="forwarded_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original message that was forwarded",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forwarded_messages",
                to="messaging_app.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_forwarded",
            field=models.BooleanField(
                default=False, help_text="Whether this message is a forwarded message"
            ),
        ),
    ]
