# Generated by Django 4.2.16 on 2025-08-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging_app", "0015_messageread"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍"),
                            ("heart", "❤️"),
                            ("haha", "😂"),
                            ("sad", "😢"),
                            ("angry", "😠"),
                            ("care", "🤗"),
                            ("dislike", "👎"),
                        ],
                        max_length=10,
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="messaging_app.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "reaction_type"],
                name="messaging_a_message_7e824b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["user", "message"], name="messaging_a_user_id_1d5be2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("user", "message")},
        ),
    ]
