# Generated by Django 4.2.16 on 2025-08-21 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging_app", "0016_create_message_reactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="messaging_app.message",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "mentioned_user"],
                        name="messaging_a_message_f576c7_idx",
                    ),
                    models.Index(
                        fields=["mentioned_user", "created_at"],
                        name="messaging_a_mention_714475_idx",
                    ),
                ],
                "unique_together": {("message", "mentioned_user")},
            },
        ),
    ]
