import os
import re

root = os.path.dirname(os.path.dirname(__file__))  # Backend
report_path = os.path.join(root, 'model_field_report.md')

model_class_re = re.compile(r'^class\s+(\w+)\s*\(.*models\.Model.*\):')
field_re = re.compile(r'^\s*(\w+)\s*=\s*models\.(\w+Field)\s*(\(|\()')
field_start_re = re.compile(r'^\s*(\w+)\s*=\s*models\.(\w+)')
paren_open_re = re.compile(r'\(')
paren_close_re = re.compile(r'\)')

apps = []
for name in os.listdir(root):
    app_path = os.path.join(root, name)
    models_path = os.path.join(app_path, 'models')
    if os.path.isdir(models_path):
        apps.append((name, models_path))

lines_out = []
lines_out.append('# Model Field Report')
lines_out.append('Generated by scripts/dump_models_report.py')
lines_out.append('')

for app_name, models_path in sorted(apps):
    lines_out.append(f'## App: {app_name}')
    py_files = [f for f in os.listdir(models_path) if f.endswith('.py')]
    if not py_files:
        lines_out.append('_No model files found_')
        lines_out.append('')
        continue
    for py in sorted(py_files):
        fp = os.path.join(models_path, py)
        with open(fp, 'r', encoding='utf-8') as fh:
            txt = fh.read()
        lines = txt.splitlines()
        current_model = None
        model_fields = {}
        i = 0
        while i < len(lines):
            line = lines[i]
            mclass = model_class_re.match(line)
            if mclass:
                if current_model:
                    # flush previous
                    lines_out.append(f'### File: {py} - Model: {current_model}')
                    if model_fields:
                        for fname, fdesc in model_fields.items():
                            lines_out.append(f'- **{fname}**: {fdesc}')
                    else:
                        lines_out.append('- _no fields found_')
                    lines_out.append('')
                current_model = mclass.group(1)
                model_fields = {}
                i += 1
                continue

            if current_model:
                # detect field assignment
                mfield = field_start_re.match(line)
                if mfield:
                    fname = mfield.group(1)
                    # capture until balanced parens
                    snippet = line.strip()
                    open_parens = len(paren_open_re.findall(line)) - len(paren_close_re.findall(line))
                    j = i + 1
                    while open_parens > 0 and j < len(lines):
                        snippet += ' ' + lines[j].strip()
                        open_parens += len(paren_open_re.findall(lines[j])) - len(paren_close_re.findall(lines[j]))
                        j += 1
                    model_fields[fname] = snippet
                    i = j
                    continue
            i += 1
        # flush last model in file
        if current_model:
            lines_out.append(f'### File: {py} - Model: {current_model}')
            if model_fields:
                for fname, fdesc in model_fields.items():
                    lines_out.append(f'- **{fname}**: {fdesc}')
            else:
                lines_out.append('- _no fields found_')
            lines_out.append('')

with open(report_path, 'w', encoding='utf-8') as out:
    out.write('\n'.join(lines_out))

print('Report written to', report_path)
