# Generated by Django 4.2.16 on 2025-09-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_profile_allow_contact_profile_allow_messaging_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="following",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("blocked", "Blocked"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="following",
            index=models.Index(fields=["status"], name="auth_app_fo_status_61dc0b_idx"),
        ),
    ]
