# Generated by Django 4.2.23 on 2025-08-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_add_missing_parent_fields'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS auth_app_profile (
                id SERIAL PRIMARY KEY,
                timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                full_name VARCHAR(450) NOT NULL,
                email_address VARCHAR(254) NOT NULL,
                school_id VARCHAR(50) NOT NULL,
                mobile_number VARCHAR(20) NOT NULL,
                sex VARCHAR(20) NOT NULL,
                civil_status VARCHAR(20) NOT NULL,
                year_of_birth DATE NOT NULL,
                present_address TEXT NOT NULL,
                permanent_address TEXT NOT NULL,
                mothers_name VARCHAR(150) NOT NULL,
                mothers_occupation VARCHAR(100) NOT NULL,
                fathers_name VARCHAR(150) NOT NULL,
                fathers_occupation VARCHAR(100) NOT NULL,
                year_graduated INTEGER NOT NULL,
                program VARCHAR(100) NOT NULL,
                present_employment_status VARCHAR(50) NOT NULL,
                employment_classification VARCHAR(50),
                present_occupation VARCHAR(255),
                employing_agency VARCHAR(255),
                user_id BIGINT NOT NULL UNIQUE REFERENCES auth_app_customuser(id) ON DELETE CASCADE,
                bio TEXT,
                last_seen TIMESTAMP WITH TIME ZONE,
                status VARCHAR(20) DEFAULT 'offline'
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS auth_app_profile;"
        ),
    ]
