# Generated by Django 4.2.23 on 2025-08-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_recreate_profile_table'),
        ('auth_app', '0006_create_missing_tables'),
    ]

    operations = [
    ]
