# Generated by Django 4.2.16 on 2025-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0006_customuser_permanent_address_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="civil_status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fathers_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fathers_occupation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="headline",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_seen",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mothers_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mothers_occupation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_address_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_barangay",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_city_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_city_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_full_address_international",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_postal_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_province_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_province_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_region_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_region_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permanent_street_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_address_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_barangay",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_city_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_city_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_full_address_international",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_postal_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_province_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_province_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_region_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_region_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="present_street_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_visibility",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="program",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="year_graduated",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="year_of_birth",
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="feedbackrecommendations",
            name="recommendations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="perceptionfurtherstudies",
            name="field_of_study",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="perceptionfurtherstudies",
            name="level_of_study",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masters", "Master's"),
                    ("doctoral", "Doctoral"),
                    ("certificate", "Certificate"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="perceptionfurtherstudies",
            name="mode_of_study",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("online", "Online"),
                    ("others", "Others"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="perceptionfurtherstudies",
            name="reasons_for_further_study",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="perceptionfurtherstudies",
            name="specialization",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employing_agency",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employment_classification",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="present_employment_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="present_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
