# Generated by Django 4.2.16 on 2025-10-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0013_fieldprivacysetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="is_current_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("high_school", "High School"),
                    ("vocational", "Vocational"),
                    ("associate", "Associate Degree"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("doctoral", "Doctoral Degree"),
                    ("certificate", "Certificate"),
                    ("diploma", "Diploma"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="college_education_relevant",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("somewhat", "Somewhat")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed_locally", "Employed Locally"),
                    ("employed_internationally", "Employed Internationally"),
                    ("self_employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="how_got_job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="is_breadwinner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[("first_job", "First Job"), ("current_job", "Current Job")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="length_of_service",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="monthly_income",
            field=models.CharField(
                blank=True,
                choices=[
                    ("less_than_15000", "Less than P15,000"),
                    ("15000_to_29999", "P15,000 - P29,999"),
                    ("30000_to_49999", "P30,000 - P49,999"),
                    ("50000_and_above", "P50,000 and above"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
