# Generated by Django 4.2.16 on 2025-11-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0025_recognition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload training certificate",
                        null=True,
                        upload_to="achievements/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_start"],
                        name="auth_app_tr_user_id_14d25e_idx",
                    ),
                    models.Index(
                        fields=["organization"], name="auth_app_tr_organiz_578b12_idx"
                    ),
                ],
            },
        ),
    ]
