# Generated by Django 4.2.16 on 2025-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0028_csestatus_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="college_education_relevant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="employment_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="how_got_job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="is_breadwinner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="job_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="monthly_income",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
