# Generated by Django 4.2.26 on 2026-02-10 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0031_remove_workhistory_is_current_job_and_more"),
    ]

    operations = [
        # Use conditional SQL drops to make this migration idempotent
        migrations.RunSQL(
            sql="ALTER TABLE IF EXISTS auth_app_workhistory DROP COLUMN IF EXISTS is_current_job;",
            reverse_sql="ALTER TABLE IF EXISTS auth_app_workhistory ADD COLUMN IF NOT EXISTS is_current_job boolean DEFAULT false;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE IF EXISTS auth_app_workhistory DROP COLUMN IF EXISTS skills;",
            reverse_sql="-- reverse for skills omitted; manual restore may be needed",
        ),
    ]
