# Generated by Django 4.2.16 on 2026-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0033_remove_workhistory_is_current_job_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="publication",
            name="auth_app_pu_user_id_e89f6e_idx",
        ),
        migrations.RemoveIndex(
            model_name="publication",
            name="auth_app_pu_publica_2d1a1a_idx",
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["name"], name="auth_app_au_name_8a853f_idx"),
        ),
        migrations.AddField(
            model_name="publication",
            name="authors_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="auth_app.author"
            ),
        ),
    ]
