# Generated by Django 4.2.26 on 2026-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0037_backfill_workhistory_is_current_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="is_related_to_undergrad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="reason_for_further_study",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="education",
            name="reason_other_specify",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="specialization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
