# Generated by Django 5.2.3 on 2025-07-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_surveyfield_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response_json',
            field=models.JSONField(blank=True, help_text='For multiple choice answers', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Single Select'), ('radio', 'Radio Button'), ('checkbox', 'Multiple Select'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='For select, radio, checkbox questions')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auth_app.surveycategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.surveyquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('user', 'question')},
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='field',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='SurveyField',
        ),
    ]
