# Generated by Django 4.2.16 on 2025-08-27 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_profile_bio_profile_last_seen_profile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_contact",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="allow_messaging",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("alumni_only", "Alumni Only"),
                    ("connections_only", "Connections Only"),
                    ("private", "Private"),
                ],
                default="alumni_only",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Following",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_mutual", models.BooleanField(default=False)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower"], name="auth_app_fo_followe_c1070d_idx"
                    ),
                    models.Index(
                        fields=["following"], name="auth_app_fo_followi_9a65a6_idx"
                    ),
                    models.Index(
                        fields=["is_mutual"], name="auth_app_fo_is_mutu_45324f_idx"
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("doctoral", "Doctoral Degree"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="auth_app_ed_user_id_01271c_idx"
                    ),
                    models.Index(
                        fields=["is_current"], name="auth_app_ed_is_curr_5139d4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("professional", "Professional"),
                            ("certification", "Certification"),
                            ("award", "Award"),
                            ("volunteer", "Volunteer Work"),
                            ("project", "Project"),
                            ("publication", "Publication"),
                            ("patent", "Patent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_achieved", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="achievements/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_achieved", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="auth_app_ac_user_id_7bf4e1_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="auth_app_ac_is_feat_0663fc_idx"
                    ),
                ],
            },
        ),
    ]
