# Generated by Django 4.2.16 on 2025-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0011_customuser_gender_alter_alumnidirectory_sex_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="sex",
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
