# Generated by Django 4.2.16 on 2025-10-13 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0012_remove_profile_sex_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldPrivacySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Visible to everyone"),
                            ("alumni_only", "Alumni Only - Visible to verified alumni"),
                            (
                                "connections_only",
                                "Connections Only - Visible to your connections",
                            ),
                            ("private", "Private - Only visible to you"),
                        ],
                        default="alumni_only",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "field_name"],
                        name="auth_app_fi_user_id_fada94_idx",
                    ),
                    models.Index(
                        fields=["visibility"], name="auth_app_fi_visibil_51b531_idx"
                    ),
                ],
                "unique_together": {("user", "field_name")},
            },
        ),
    ]
