# Generated by Django 4.2.16 on 2025-10-14 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0014_update_workhistory_simplify_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workhistory",
            name="college_education_relevant",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="how_got_job",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="is_breadwinner",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="job_type",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="monthly_income",
        ),
    ]
