# Generated by Django 4.2.16 on 2025-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0016_add_user_skill_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldprivacysetting",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("everyone", "For Everyone"),
                    ("connections_only", "For Connections"),
                    ("only_me", "Only for Me"),
                ],
                default="connections_only",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "For Everyone"),
                    ("connections_only", "For Connections"),
                    ("private", "Only for Me"),
                ],
                default="connections_only",
                max_length=20,
            ),
        ),
    ]
