# Generated by Django 4.2.16 on 2025-10-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0018_update_privacy_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionPrivacySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        choices=[
                            ("about", "About Me"),
                            ("contact", "Contact Information"),
                            ("education", "Education"),
                            ("experience", "Work Experience"),
                            ("skills", "Skills & Expertise"),
                            ("achievements", "Awards & Achievements"),
                            ("network", "Professional Network"),
                            ("posts", "Posts & Activities"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "For Everyone"),
                            ("alumni_only", "Alumni Only"),
                            ("connections_only", "For Connections"),
                            ("private", "Only for Me"),
                        ],
                        default="alumni_only",
                        max_length=20,
                    ),
                ),
                (
                    "override_field_settings",
                    models.BooleanField(
                        default=False,
                        help_text="If True, section setting overrides individual field settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "section_name"],
                        name="auth_app_se_user_id_d06556_idx",
                    ),
                    models.Index(
                        fields=["visibility"], name="auth_app_se_visibil_3bea6f_idx"
                    ),
                    models.Index(
                        fields=["override_field_settings"],
                        name="auth_app_se_overrid_73255f_idx",
                    ),
                ],
                "unique_together": {("user", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="PrivacyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("open", "Open Profile"),
                            ("professional", "Professional"),
                            ("private", "Private"),
                            ("selective", "Selective"),
                            ("custom", "Custom"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile_type"], name="auth_app_pr_profile_54cbc8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="auth_app_pr_is_acti_fe7bad_idx"
                    ),
                ],
            },
        ),
    ]
