# Generated by Django 4.2.16 on 2025-10-22 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0020_merge_20251022_0853"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacyprofile",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="sectionprivacysetting",
            name="auth_app_se_user_id_d06556_idx",
        ),
        migrations.RemoveIndex(
            model_name="sectionprivacysetting",
            name="auth_app_se_visibil_3bea6f_idx",
        ),
        migrations.RemoveIndex(
            model_name="sectionprivacysetting",
            name="auth_app_se_overrid_73255f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="sectionprivacysetting",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="PrivacyProfile",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="override_field_settings",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="section_name",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sectionprivacysetting",
            name="visibility",
        ),
    ]
