# Generated by Django 4.2.16 on 2025-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0022_workhistory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("transgender", "Transgender"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other_specify", "Other (please specify)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("transgender", "Transgender"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other_specify", "Other (please specify)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
