# Generated by Django 4.2.26 on 2026-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0030_alter_workhistory_make_fields_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workhistory",
            name="is_current_job",
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="skills",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("connections_only", "Connections Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
