# Generated by Django 4.2.16 on 2025-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0002_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("applaud", "👏"),
                    ("sad", "�"),
                    ("laugh", "�"),
                    ("heart", "❤️"),
                    ("support", "🤝"),
                ],
                max_length=20,
            ),
        ),
    ]
