# Generated by Django 4.2.16 on 2025-08-25 10:43

from django.db import migrations


def migrate_reaction_types(apps, schema_editor):
    """
    Migrate old Facebook-style reactions to new LinkedIn-style reactions
    """
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Mapping from old reactions to new ones
    reaction_mapping = {
        'love': 'heart',     # 😍 → ❤️
        'wow': 'applaud',    # 😮 → 👏  
        'angry': 'sad',      # 😡 → 😢
        'haha': 'laugh',     # 😂 stays the same
        'like': 'like',      # 👍 stays the same
        'sad': 'sad',        # 😢 stays the same
    }
    
    for old_type, new_type in reaction_mapping.items():
        Reaction.objects.filter(reaction_type=old_type).update(reaction_type=new_type)


def reverse_migrate_reaction_types(apps, schema_editor):
    """
    Reverse the migration if needed
    """
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Reverse mapping
    reverse_mapping = {
        'heart': 'love',
        'applaud': 'wow',
        'laugh': 'haha',
        'like': 'like',
        'sad': 'sad',
        'support': 'like',  # Default fallback
    }
    
    for new_type, old_type in reverse_mapping.items():
        Reaction.objects.filter(reaction_type=new_type).update(reaction_type=old_type)


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0003_update_reaction_types"),
    ]

    operations = [
        migrations.RunPython(migrate_reaction_types, reverse_migrate_reaction_types),
    ]
