# Generated by Django 4.2.16 on 2025-08-25 10:54

from django.db import migrations


def convert_reactions(apps, schema_editor):
    """Convert Facebook-style reactions to LinkedIn-style reactions"""
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Mapping from old Facebook reactions to new LinkedIn reactions
    reaction_mapping = {
        'love': 'heart',     # love ❤️ -> heart ❤️
        'laugh': 'laugh',    # laugh 😄 -> laugh 😂 (same but different emoji)
        'wow': 'applaud',    # wow 😮 -> applaud 👏 (amazement -> applause)
        'angry': 'sad',      # angry 😡 -> sad 😢 (negative emotion)
        'like': 'like',      # like 👍 -> like 👍 (same)
        'sad': 'sad',        # sad 😢 -> sad 😢 (same)
    }
    
    for old_type, new_type in reaction_mapping.items():
        Reaction.objects.filter(reaction_type=old_type).update(reaction_type=new_type)
    
    print(f"Converted reactions: {reaction_mapping}")


def reverse_reactions(apps, schema_editor):
    """Reverse the reaction conversion"""
    Reaction = apps.get_model('posts_app', 'Reaction')
    
    # Reverse mapping
    reverse_mapping = {
        'heart': 'love',
        'laugh': 'laugh',
        'applaud': 'wow',
        'like': 'like',
        'sad': 'sad',
    }
    
    for new_type, old_type in reverse_mapping.items():
        Reaction.objects.filter(reaction_type=new_type).update(reaction_type=old_type)


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0004_migrate_existing_reactions"),
    ]

    operations = [
        migrations.RunPython(convert_reactions, reverse_reactions),
    ]
