# Generated by Django 4.2.16 on 2025-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0007_alter_reaction_reaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
