# Generated by Django 4.2.16 on 2025-10-22 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0004_post_approved_at_post_approved_by_and_more"),
        ("posts_app", "0011_alter_postreport_reason"),
    ]

    operations = []
