# Generated by Django 4.2.16 on 2025-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0005_encrypt_content_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(upload_to="attachments/"),
        ),
    ]
