# Generated by Django 4.2.16 on 2025-08-15 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging_app", "0010_linkpreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MutedConversation",
        ),
    ]
