# Generated by Django 4.2.16 on 2025-08-22 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display (lower numbers first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": [1, 2]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Survey Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question text that will be displayed"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("textarea", "Long Text Area"),
                            ("radio", "Single Choice (Radio)"),
                            ("checkbox", "Multiple Choice (Checkbox)"),
                            ("select", "Dropdown Select"),
                            ("number", "Number Input"),
                            ("email", "Email Input"),
                            ("date", "Date Picker"),
                            ("rating", "Rating Scale (1-5)"),
                            ("yes_no", "Yes/No Question"),
                            ("file", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "placeholder_text",
                    models.CharField(
                        blank=True,
                        help_text="Placeholder text for input fields",
                        max_length=255,
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        help_text="Additional help text for the question",
                        max_length=500,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of options for choice questions. Example: ['Option 1', 'Option 2']",
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "min_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum value for number/rating questions",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum value for number/rating questions",
                        null=True,
                    ),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum character length for text inputs",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within category (lower numbers first)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="survey_app.surveycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": [1, 2]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order", "question_text"],
                "unique_together": {("category", "question_text")},
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default template for new registrations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveycategory",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveytemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "category")},
            },
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="categories",
            field=models.ManyToManyField(
                through="survey_app.SurveyTemplateCategory",
                to="survey_app.surveycategory",
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"user_type__in": [1, 2]},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(help_text="Stores the actual response data"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="survey_app.surveyquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("user", "question")},
            },
        ),
    ]
