# Generated by Django 4.2.16 on 2025-08-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="depends_on_question",
            field=models.ForeignKey(
                blank=True,
                help_text="Question this depends on for conditional display",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_app.surveyquestion",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="depends_on_value",
            field=models.TextField(
                blank=True,
                help_text="Value that triggers display of this question (JSON for multiple values)",
            ),
        ),
    ]
