# Generated by Django 4.2.16 on 2025-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0003_add_category_conditional_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycategory",
            name="include_in_registration",
            field=models.BooleanField(
                default=False,
                help_text="Include this category in the public registration survey",
            ),
        ),
    ]
