# Generated by Django 4.2.16 on 2025-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0008_remove_old_template_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveycategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
