# Generated by Django 4.2.16 on 2025-11-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0009_remove_category_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Input"),
                    ("textarea", "Long Text Area"),
                    ("radio", "Single Choice (Radio)"),
                    ("checkbox", "Multiple Choice (Checkbox)"),
                    ("select", "Dropdown Select"),
                    ("number", "Number Input"),
                    ("year", "Year (YYYY)"),
                    ("email", "Email Input"),
                    ("date", "Date Picker"),
                    ("rating", "Rating Scale (1-5)"),
                    ("yes_no", "Yes/No Question"),
                    ("file", "File Upload"),
                ],
                max_length=20,
            ),
        ),
    ]
