# Generated by Django 4.2.16 on 2025-08-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0002_surveyquestion_depends_on_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycategory",
            name="depends_on_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category this depends on for conditional display",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_app.surveycategory",
            ),
        ),
        migrations.AddField(
            model_name="surveycategory",
            name="depends_on_question_text",
            field=models.CharField(
                blank=True,
                help_text="Specific question text within the dependency category",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="surveycategory",
            name="depends_on_value",
            field=models.TextField(
                blank=True,
                help_text="Value that triggers display of this category (JSON for multiple values)",
            ),
        ),
    ]
