# Generated by Django 4.2.16 on 2025-11-15 06:42

from django.db import migrations


def set_existing_registration_categories(apps, schema_editor):
    """
    Set include_in_registration=True for existing categories that should be in registration.
    This preserves current behavior where all active categories except two specific ones
    were shown in registration.
    """
    SurveyCategory = apps.get_model('survey_app', 'SurveyCategory')
    
    # Categories that were previously excluded from registration
    excluded_categories = ['Alumni Verification', 'Personal & Demographic Information']
    
    # Set include_in_registration=True for all active categories except the excluded ones
    # This preserves the current registration behavior
    categories_to_include = SurveyCategory.objects.filter(
        is_active=True
    ).exclude(
        name__in=excluded_categories
    )
    
    count = categories_to_include.update(include_in_registration=True)
    
    print(f"✅ Set include_in_registration=True for {count} existing categories")
    
    # Explicitly set False for excluded categories
    excluded_count = SurveyCategory.objects.filter(
        name__in=excluded_categories
    ).update(include_in_registration=False)
    
    print(f"✅ Set include_in_registration=False for {excluded_count} excluded categories")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation - set all categories back to False
    """
    SurveyCategory = apps.get_model('survey_app', 'SurveyCategory')
    SurveyCategory.objects.all().update(include_in_registration=False)


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0004_add_include_in_registration"),
    ]

    operations = [
        migrations.RunPython(set_existing_registration_categories, reverse_migration),
    ]
