# Generated by Django 4.2.16 on 2025-11-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0006_add_form_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycategory",
            name="page_break",
            field=models.BooleanField(
                default=True,
                help_text="Treat this category as a separate page/section in multi-page surveys",
            ),
        ),
        migrations.AddField(
            model_name="surveycategory",
            name="page_description",
            field=models.TextField(
                blank=True,
                help_text="Optional description shown at the top of this page/section",
            ),
        ),
        migrations.AddField(
            model_name="surveycategory",
            name="page_title",
            field=models.CharField(
                blank=True,
                help_text="Optional page title (defaults to category name if blank)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="allow_response_editing",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to edit their responses after submission",
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="collect_email",
            field=models.BooleanField(
                default=True, help_text="Collect respondent email addresses"
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="limit_one_response",
            field=models.BooleanField(
                default=True, help_text="Limit to one response per user"
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="response_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional end date for accepting responses",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="response_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional start date for accepting responses",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="branching",
            field=models.JSONField(
                blank=True,
                help_text="Branching logic: map answer options to target categories. Example: {'option_1': {'action': 'goto', 'target_category_id': 5}, 'default': {'action': 'continue'}}",
                null=True,
            ),
        ),
    ]
