# Generated by Django 4.2.16 on 2025-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app", "0010_add_year_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveytemplate",
            name="public_slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique slug for shareable survey link (auto-generated when share_enabled=True)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="share_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow admins to view and share this survey link (read-only distribution)",
            ),
        ),
    ]
