# Generated by Django 4.2.16 on 2025-09-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0004_following_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alumnidirectory",
            name="auth_app_al_school__bbac3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="alumnidirectory",
            name="auth_app_al_first_n_f6a0bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="auth_app_cu_school__efcc62_idx",
        ),
        migrations.RenameField(
            model_name="alumnidirectory",
            old_name="gender",
            new_name="sex",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="gender",
            new_name="sex",
        ),
        migrations.RemoveField(
            model_name="alumnidirectory",
            name="school_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="school_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="school_id",
        ),
        migrations.AddIndex(
            model_name="alumnidirectory",
            index=models.Index(
                fields=[
                    "first_name",
                    "last_name",
                    "birth_date",
                    "program",
                    "year_graduated",
                ],
                name="auth_app_al_first_n_51f170_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=[
                    "first_name",
                    "last_name",
                    "birth_date",
                    "program",
                    "year_graduated",
                ],
                name="auth_app_cu_first_n_d8e283_idx",
            ),
        ),
    ]
