# Generated by Django 4.2.23 on 2025-08-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_fix_workhistory_schema'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create SkillsRelevance table
            CREATE TABLE IF NOT EXISTS auth_app_skillsrelevance (
                id SERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL UNIQUE REFERENCES auth_app_customuser(id) ON DELETE CASCADE,
                critical_thinking INTEGER NOT NULL CHECK (critical_thinking >= 1 AND critical_thinking <= 5),
                communication INTEGER NOT NULL CHECK (communication >= 1 AND communication <= 5),
                innovation INTEGER NOT NULL CHECK (innovation >= 1 AND innovation <= 5),
                collaboration INTEGER NOT NULL CHECK (collaboration >= 1 AND collaboration <= 5),
                leadership INTEGER NOT NULL CHECK (leadership >= 1 AND leadership <= 5),
                productivity_accountability INTEGER NOT NULL CHECK (productivity_accountability >= 1 AND productivity_accountability <= 5),
                entrepreneurship INTEGER NOT NULL CHECK (entrepreneurship >= 1 AND entrepreneurship <= 5),
                global_citizenship INTEGER NOT NULL CHECK (global_citizenship >= 1 AND global_citizenship <= 5),
                adaptability INTEGER NOT NULL CHECK (adaptability >= 1 AND adaptability <= 5),
                accessing_analyzing_synthesizing_info INTEGER NOT NULL CHECK (accessing_analyzing_synthesizing_info >= 1 AND accessing_analyzing_synthesizing_info <= 5)
            );
            
            -- Create CurriculumRelevance table
            CREATE TABLE IF NOT EXISTS auth_app_curriculumrelevance (
                id SERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL UNIQUE REFERENCES auth_app_customuser(id) ON DELETE CASCADE,
                general_education INTEGER NOT NULL CHECK (general_education >= 1 AND general_education <= 5),
                core_major INTEGER NOT NULL CHECK (core_major >= 1 AND core_major <= 5),
                special_professional INTEGER NOT NULL CHECK (special_professional >= 1 AND special_professional <= 5),
                electives INTEGER NOT NULL CHECK (electives >= 1 AND electives <= 5),
                internship_ojt INTEGER NOT NULL CHECK (internship_ojt >= 1 AND internship_ojt <= 5),
                co_curricular_activities INTEGER NOT NULL CHECK (co_curricular_activities >= 1 AND co_curricular_activities <= 5),
                extra_curricular_activities INTEGER NOT NULL CHECK (extra_curricular_activities >= 1 AND extra_curricular_activities <= 5)
            );
            
            -- Create PerceptionFurtherStudies table
            CREATE TABLE IF NOT EXISTS auth_app_perceptionfurtherstudies (
                id SERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL UNIQUE REFERENCES auth_app_customuser(id) ON DELETE CASCADE,
                competitiveness INTEGER NOT NULL CHECK (competitiveness >= 1 AND competitiveness <= 5),
                pursued_further_studies BOOLEAN NOT NULL,
                mode_of_study VARCHAR(50),
                level_of_study VARCHAR(50),
                field_of_study VARCHAR(100),
                specialization VARCHAR(100),
                related_to_undergrad BOOLEAN,
                reasons_for_further_study TEXT
            );
            
            -- Add constraints for choices in PerceptionFurtherStudies
            ALTER TABLE auth_app_perceptionfurtherstudies ADD CONSTRAINT auth_app_perceptionfurtherstudies_mode_of_study_check 
            CHECK (mode_of_study IS NULL OR mode_of_study IN ('full_time', 'part_time', 'online', 'others'));
            
            ALTER TABLE auth_app_perceptionfurtherstudies ADD CONSTRAINT auth_app_perceptionfurtherstudies_level_of_study_check 
            CHECK (level_of_study IS NULL OR level_of_study IN ('masters', 'doctoral', 'certificate'));
            
            -- Create FeedbackRecommendations table
            CREATE TABLE IF NOT EXISTS auth_app_feedbackrecommendations (
                id SERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL UNIQUE REFERENCES auth_app_customuser(id) ON DELETE CASCADE,
                recommendations TEXT
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS auth_app_skillsrelevance CASCADE;
            DROP TABLE IF EXISTS auth_app_curriculumrelevance CASCADE;
            DROP TABLE IF EXISTS auth_app_perceptionfurtherstudies CASCADE;
            DROP TABLE IF EXISTS auth_app_feedbackrecommendations CASCADE;
            """
        ),
    ]
