# Generated by Django 4.2.16 on 2025-10-11 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0008_remove_profile_duplicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("widowed", "Widowed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="employing_agency",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="employment_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("government", "Government"),
                    ("private", "Private"),
                    ("ngo", "NGO"),
                    ("freelance", "Freelance"),
                    ("business_owner", "Business Owner"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fathers_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mothers_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mothers_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_address_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("philippines", "Philippines"),
                    ("international", "International"),
                ],
                default="philippines",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_barangay",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_city_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_city_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_full_address_international",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_province_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_province_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_region_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_region_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="permanent_street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_address_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("philippines", "Philippines"),
                    ("international", "International"),
                ],
                default="philippines",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_barangay",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_city_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_city_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed_locally", "Employed Locally"),
                    ("employed_internationally", "Employed Internationally"),
                    ("self_employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_full_address_international",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_province_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_province_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_region_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_region_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="present_street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="program",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_graduated",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_category",
                    models.CharField(
                        choices=[("present", "Present"), ("permanent", "Permanent")],
                        max_length=20,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("philippines", "Philippines"),
                            ("international", "International"),
                        ],
                        default="philippines",
                        max_length=20,
                    ),
                ),
                ("region_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "province_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "province_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city_name", models.CharField(blank=True, max_length=100, null=True)),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("full_address", models.TextField(blank=True, null=True)),
                ("normalized_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "address_category"],
                        name="auth_app_ad_user_id_15b434_idx",
                    ),
                    models.Index(
                        fields=["address_type"], name="auth_app_ad_address_84fbca_idx"
                    ),
                    models.Index(
                        fields=["city_name"], name="auth_app_ad_city_na_ae247f_idx"
                    ),
                    models.Index(
                        fields=["postal_code"], name="auth_app_ad_postal__d26c00_idx"
                    ),
                ],
                "unique_together": {("user", "address_category")},
            },
        ),
    ]
