# Generated by Django 4.2.16 on 2025-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0010_remove_legacy_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alumnidirectory",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                null=True,
            ),
        ),
    ]
