# Generated by Django 4.2.16 on 2025-10-15 06:27

from django.db import migrations


def update_privacy_values(apps, schema_editor):
    """Update old privacy values to new format"""
    FieldPrivacySetting = apps.get_model('auth_app', 'FieldPrivacySetting')
    Profile = apps.get_model('auth_app', 'Profile')
    
    # Update FieldPrivacySetting values
    FieldPrivacySetting.objects.filter(visibility='public').update(visibility='everyone')
    FieldPrivacySetting.objects.filter(visibility='private').update(visibility='only_me')
    FieldPrivacySetting.objects.filter(visibility='alumni_only').update(visibility='connections_only')
    
    # Update Profile visibility values if they exist
    Profile.objects.filter(profile_visibility='public').update(profile_visibility='everyone')
    Profile.objects.filter(profile_visibility='private').update(profile_visibility='only_me')
    Profile.objects.filter(profile_visibility='alumni_only').update(profile_visibility='connections_only')


def reverse_privacy_values(apps, schema_editor):
    """Reverse the privacy value updates"""
    FieldPrivacySetting = apps.get_model('auth_app', 'FieldPrivacySetting')
    Profile = apps.get_model('auth_app', 'Profile')
    
    # Reverse FieldPrivacySetting values
    FieldPrivacySetting.objects.filter(visibility='everyone').update(visibility='public')
    FieldPrivacySetting.objects.filter(visibility='only_me').update(visibility='private')
    FieldPrivacySetting.objects.filter(visibility='connections_only').update(visibility='alumni_only')
    
    # Reverse Profile visibility values if they exist
    Profile.objects.filter(profile_visibility='everyone').update(profile_visibility='public')
    Profile.objects.filter(profile_visibility='only_me').update(profile_visibility='private')
    Profile.objects.filter(profile_visibility='connections_only').update(profile_visibility='alumni_only')


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0017_update_privacy_choices"),
    ]

    operations = [
        migrations.RunPython(update_privacy_values, reverse_privacy_values),
    ]
