# Generated by Django 4.2.16 on 2025-10-22 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0007_merge_20250831_2208"),
        ("auth_app", "0019_sectionprivacysetting_privacyprofile"),
    ]

    operations = []
