# Generated by Django 4.2.16 on 2025-11-24 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0023_alter_customuser_gender_alter_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("active", "Active Member"),
                            ("inactive", "Inactive Member"),
                            ("honorary", "Honorary Member"),
                            ("lifetime", "Lifetime Member"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("date_ended", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "membership_type"],
                        name="auth_app_me_user_id_7278a1_idx",
                    ),
                    models.Index(
                        fields=["organization_name"],
                        name="auth_app_me_organiz_e02009_idx",
                    ),
                ],
            },
        ),
    ]
