# Generated by Django 4.2.16 on 2025-11-24 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0024_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(max_length=255)),
                ("date_received", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificate or award document",
                        null=True,
                        upload_to="achievements/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_received", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_received"],
                        name="auth_app_re_user_id_91621b_idx",
                    ),
                    models.Index(
                        fields=["issuing_organization"],
                        name="auth_app_re_issuing_92234f_idx",
                    ),
                ],
            },
        ),
    ]
