# Generated by Django 4.2.16 on 2025-11-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0026_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book"),
                            ("thesis", "Thesis/Dissertation"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.CharField(help_text="List of authors", max_length=500),
                ),
                ("date_published", models.DateField()),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to publication", null=True
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_published", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_published"],
                        name="auth_app_pu_user_id_e89f6e_idx",
                    ),
                    models.Index(
                        fields=["publication_type"],
                        name="auth_app_pu_publica_2d1a1a_idx",
                    ),
                ],
            },
        ),
    ]
