# Generated by Django 4.2.16 on 2025-11-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0027_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSEStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("self_employed", "Self-Employed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        default="unemployed",
                        max_length=20,
                    ),
                ),
                (
                    "current_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cse_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CSE Status",
                "verbose_name_plural": "CSE Statuses",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_type", models.CharField(max_length=255)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_issued", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issuing_body", models.CharField(max_length=255)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificate document",
                        null=True,
                        upload_to="achievements/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_issued"],
                        name="auth_app_ce_user_id_b9096a_idx",
                    ),
                    models.Index(
                        fields=["certificate_type"],
                        name="auth_app_ce_certifi_370e5e_idx",
                    ),
                ],
            },
        ),
    ]
