# Generated by Django 4.2.26 on 2026-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0030_alter_workhistory_make_fields_nullable"),
    ]

    operations = [
        # Use conditional SQL drops so migration is safe on DBs
        # where these columns might already be removed.
        migrations.RunSQL(
            sql="ALTER TABLE IF EXISTS auth_app_workhistory DROP COLUMN IF EXISTS is_current_job;",
            reverse_sql="ALTER TABLE IF EXISTS auth_app_workhistory ADD COLUMN IF NOT EXISTS is_current_job boolean DEFAULT false;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE IF EXISTS auth_app_workhistory DROP COLUMN IF EXISTS skills;",
            reverse_sql="-- reverse operation for skills is non-trivial; skipping",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("connections_only", "Connections Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
